
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
test:
  <<: *default
  database: pics_spdt
production:
  <<: *default
  database: pics_spdt
  username: user
  url: <%= ENV["DATABASE_URL"] %>
